2024-02-25 16:16:31,363 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-02-25 16:16:31,363 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\instabot\bot\bot.py
2024-02-25 16:16:31,364 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-02-25 16:16:34,292 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2024-02-25 16:16:34,298 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2024-02-25 16:16:34,298 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2024-02-25 16:16:34,298 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2024-02-25 16:21:34,782 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2024-02-25 16:21:34,782 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2024-02-25 16:21:34,782 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2024-02-25 16:21:34,783 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 10 minutes.
